# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileB.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fileB(object):
    def setupUi(self, fileB):
        fileB.setObjectName("fileB")
        fileB.resize(679, 523)
        self.gridLayout = QtWidgets.QGridLayout(fileB)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(fileB)
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(fileB)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowser_2.setStyleSheet("    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout.addWidget(self.textBrowser_2, 1, 1, 1, 2)
        self.PushButton_2 = PushButton(fileB)
        self.PushButton_2.setObjectName("PushButton_2")
        self.gridLayout.addWidget(self.PushButton_2, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(fileB)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(fileB)
        self.textBrowser_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.textBrowser_3.setStyleSheet("    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout.addWidget(self.textBrowser_3, 2, 1, 1, 2)
        self.PushButton_3 = PushButton(fileB)
        self.PushButton_3.setObjectName("PushButton_3")
        self.gridLayout.addWidget(self.PushButton_3, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(fileB)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 2)
        self.textBrowser = QtWidgets.QTextBrowser(fileB)
        self.textBrowser.setStyleSheet("    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 4, 0, 1, 4)
        self.PushButton = PushButton(fileB)
        self.PushButton.setObjectName("PushButton")
        self.gridLayout.addWidget(self.PushButton, 5, 0, 1, 4)

        self.retranslateUi(fileB)
        QtCore.QMetaObject.connectSlotsByName(fileB)

    def retranslateUi(self, fileB):
        _translate = QtCore.QCoreApplication.translate
        fileB.setWindowTitle(_translate("fileB", "Form"))
        self.label_2.setText(_translate("fileB", "<html><head/><body><p><span style=\" font-size:14pt;\">读取位置：</span></p></body></html>"))
        self.PushButton_2.setText(_translate("fileB", "选择文段"))
        self.label_3.setText(_translate("fileB", "<html><head/><body><p><span style=\" font-size:14pt;\">存储位置：</span></p></body></html>"))
        self.PushButton_3.setText(_translate("fileB", "新文件存储位置"))
        self.label.setText(_translate("fileB", "<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">当前文本：</span></p></body></html>"))
        self.PushButton.setText(_translate("fileB", "开始检测"))
from qfluentwidgets import PushButton
