# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_File(object):
    def setupUi(self, File):
        File.setObjectName("File")
        File.resize(538, 471)
        self.gridLayout = QtWidgets.QGridLayout(File)
        self.gridLayout.setObjectName("gridLayout")
        self.PushButton = PushButton(File)
        self.PushButton.setObjectName("PushButton")
        self.gridLayout.addWidget(self.PushButton, 1, 0, 1, 1)
        self.PushButton_2 = PushButton(File)
        self.PushButton_2.setObjectName("PushButton_2")
        self.gridLayout.addWidget(self.PushButton_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(File)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(File)
        QtCore.QMetaObject.connectSlotsByName(File)

    def retranslateUi(self, File):
        _translate = QtCore.QCoreApplication.translate
        File.setWindowTitle(_translate("File", "Form"))
        self.PushButton.setText(_translate("File", "查看图库"))
        self.PushButton_2.setText(_translate("File", "导入图像"))
        self.label.setText(_translate("File", "<html><head/><body><p><br/></p></body></html>"))
from qfluentwidgets import PushButton
