# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YU.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YU(object):
    def setupUi(self, YU):
        YU.setObjectName("YU")
        YU.resize(571, 523)
        self.gridLayout = QtWidgets.QGridLayout(YU)
        self.gridLayout.setObjectName("gridLayout")
        self.PushButton = PushButton(YU)
        self.PushButton.setObjectName("PushButton")
        self.gridLayout.addWidget(self.PushButton, 2, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(YU)
        self.textBrowser.setStyleSheet("    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    border: 1px solid rgba(0, 0, 0, 13);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 100);\n"
"    border-radius: 5px;\n"
'font: 30pt "黑体";'
"    /* font: 14px \"Segoe UI\", \"Microsoft YaHei\"; */\n"
"    padding: 0px 10px;\n"
"    selection-background-color: #00a7b3;")
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)

        self.retranslateUi(YU)
        QtCore.QMetaObject.connectSlotsByName(YU)

    def retranslateUi(self, YU):
        _translate = QtCore.QCoreApplication.translate
        YU.setWindowTitle(_translate("YU", "Form"))
        self.PushButton.setText(_translate("YU", "开始检测"))
from qfluentwidgets import PushButton
