# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'YUC.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YUC(object):
    def setupUi(self, YU):
        YU.setObjectName("YUC")
        YU.resize(571, 523)
        self.gridLayout = QtWidgets.QGridLayout(YU)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.TextEdit = TextEdit(YU)
        self.TextEdit.setObjectName("TextEdit")
        self.gridLayout.addWidget(self.TextEdit, 100, 0, 2, 2)
        self.PushButton = PushButton(YU)
        self.PushButton.setObjectName("PushButton")
        self.gridLayout.addWidget(self.PushButton, 100, 2, 1, 1)
        self.PushButton_2 = PushButton(YU)
        self.PushButton_2.setObjectName("PushButton_2")
        self.gridLayout.addWidget(self.PushButton_2, 101, 2, 1, 1)

        self.retranslateUi(YU)
        QtCore.QMetaObject.connectSlotsByName(YU)

    def retranslateUi(self, YU):
        _translate = QtCore.QCoreApplication.translate
        YU.setWindowTitle(_translate("YU", "Form"))
        self.PushButton.setText(_translate("YU", "清空文本"))
        self.PushButton_2.setText(_translate("YU", "开始识别"))
        self.PushButton_2.clicked.connect(self.begin2)
        self.PushButton_2.clicked.connect(self.begin4)
        self.PushButton.clicked.connect(self.clear_layout)
from qfluentwidgets import PushButton, TextEdit
